export const FORGOT_PASSWORD_CHANGE_USERNAME = "FORGOT_PASSWORD_CHANGE_USERNAME";
export const FORGOT_PASSWORD_FIND_BY_USERNAME_SUCCESS = "FORGOT_PASSWORD_FIND_BY_USERNAME_SUCCESS";

export const FORGOT_PASSWORD_CHANGE_RECOVER_METHOD = "FORGOT_PASSWORD_CHANGE_RECOVER_METHOD";
export const FORGOT_PASSWORD_SENT_VERIFICATION_CODE = "FORGOT_PASSWORD_SENT_VERIFICATION_CODE";

export const FORGOT_PASSWORD_CHANGE_VERIFICATION_CODE = "FORGOT_PASSWORD_CHANGE_VERIFICATION_CODE";
export const FORGOT_PASSWORD_VERIFY_CODE_SUCCESS = "FORGOT_PASSWORD_VERIFY_CODE_SUCCESS";

export const FORGOT_PASSWORD_CHANGE_NEW_PASSWORD = "FORGOT_PASSWORD_CHANGE_NEW_PASSWORD";
export const FORGOT_PASSWORD_CHANGE_VERIFY_PASSWORD = "FORGOT_PASSWORD_CHANGE_VERIFY_PASSWORD";
export const FORGOT_PASSWORD_NEW_PASSWORD_SUCCESS = "FORGOT_PASSWORD_NEW_PASSWORD_SUCCESS";

export const FORGOT_PASSWORD_CHANGE_STEP = "FORGOT_PASSWORD_CHANGE_STEP";
