export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const LOGIN_CHANGE_USERNAME = "LOGIN_CHANGE_USERNAME";
export const LOGIN_CHANGE_PASSWORD = "LOGIN_CHANGE_PASSWORD";
export const LOGIN_CHANGE_REMEMBER_ME = "LOGIN_CHANGE_REMEMBER_ME";
export const LOGIN_STATUS = "LOGIN_STATUS";

export const REGISTER_CHANGE_USERNAME = "REGISTER_CHANGE_USERNAME";
export const REGISTER_CHANGE_PASSWORD = "REGISTER_CHANGE_PASSWORD";
export const REGISTER_CHANGE_EMAIL = "REGISTER_CHANGE_EMAIL";
export const REGISTER_STATUS = "REGISTER_STATUS";

export const HOME_PAGE_IN = "HOME_PAGE_IN";
export const HOME_PAGE_LEAVE = "HOME_PAGE_LEAVE";
export const RECENT_PROPERTIES_GET_SUCCESS = "RECENT_PROPERTIES_GET_SUCCESS";

export const PROPERTY_CREATE_CHANGE_NAME = "PROPERTY_CREATE_CHANGE_NAME";
export const PROPERTY_CREATE_CHANGE_STATUS = "PROPERTY_CREATE_CHANGE_STATUS";
export const PROPERTY_CREATE_CHANGE_IMAGES = "PROPERTY_CREATE_CHANGE_IMAGES";
export const PROPERTY_CREATE_SUCCESS = "PROPERTY_CREATE_SUCCESS";
export const PROPERTY_CREATE_IN = "PROPERTY_CREATE_IN";
export const PROPERTY_CREATE_LEAVE = "PROPERTY_CREATE_LEAVE";

export const PROPERTY_UPDATE_FIND_BY_ID_SUCCESS = "PROPERTY_UPDATE_FIND_BY_ID_SUCCESS";
export const PROPERTY_UPDATE_CHANGE_NAME = "PROPERTY_UPDATE_CHANGE_NAME";
export const PROPERTY_UPDATE_CHANGE_STATUS = "PROPERTY_UPDATE_CHANGE_STATUS";
export const PROPERTY_UPDATE_CHANGE_IMAGES = "PROPERTY_UPDATE_CHANGE_IMAGES";
export const PROPERTY_UPDATE_SUCCESS = "PROPERTY_UPDATE_SUCCESS";
export const PROPERTY_UPDATE_IN = "PROPERTY_UPDATE_IN";
export const PROPERTY_UPDATE_LEAVE = "PROPERTY_UPDATE_LEAVE";

export const PROPERTY_VIEW_FIND_BY_ID_SUCCESS = "PROPERTY_VIEW_FIND_BY_ID_SUCCESS";
export const PROPERTY_VIEW_LEAVE = "PROPERTY_VIEW_LEAVE";
