version: "3.9"

services:
  frontend:
    image: thainguyen1093/frontend_image
    build: 
      context: ../frontend
    container_name: frontend_container
    ports: 
      - "80:80"

  backend:
    image: thainguyen1093/backend_image
    build: 
      context: ../backend
    container_name: backend_container
    ports: 
      - "8080:8080"
    depends_on:
      - "database"

  database:
    image: mysql:8.0.24
    container_name: mysql_container
    ports: 
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: java_react

volumes: 
  mysql_volume: