version: "3.9"

services:
  database:
    image: mysql:8.0.23
    container_name: mysql_container
    ports: 
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=java_react

volumes: 
  mysql_volume: